server:
  port: 8776
  tomcat:
    uri-encoding: UTF-8
  servlet:
    session:
      cookie:
        name: feedback

spring:
  application:
    name: feedback

  http:
    multipart:
      location: /data/upload_tmp

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
        enable_lazy_load_no_trans: true
    open-in-view: true
    database: oracle

  message:
    deadline: 2

  jackson:
    default-property-inclusion: non_null
  aop:
    auto: true

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:oracle:thin:@localhost:1521:young
    url: jdbc:oracle:thin:@10.32.250.83:1521:fyplatform
    username: fyplatform
    password: 123456
    driver-class-name: oracle.jdbc.OracleDriver
    filters: stat,wall,slf4j
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x' from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20


  redis:
    database: 0
    host: 10.32.250.87
#    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: 1ms
        max-idle: 8
        min-idle: 0
    timeout: 10000ms

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.feedback.model

pagehelper:
  helperDialect: oracle
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#        defaultZone: http://10.32.250.85:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5000
    lease-expiration-duration-in-seconds: 5000