server:
    port: 8772
    tomcat:
      uri-encoding: UTF-8
    servlet:
      session:
        cookie:
          name: attendance

spring:
    application:
      name: attendance

    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.Oracle10gDialect
          enable_lazy_load_no_trans: true
      open-in-view: true
      database: oracle

    jackson:
      default-property-inclusion: non_null
    aop:
      auto: true

    datasource:
      name: dataSource
#      url: jdbc:oracle:thin:@localhost:1521:young
      url: jdbc:oracle:thin:@10.32.250.83:1521:fyplatform
      username: fyplatform
#      username: scott
      password: 123456
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: oracle.jdbc.OracleDriver
      filters: stat,wall,slf4j
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20


  #redis配置
    redis:
      database: 0
#      host: 10.32.250.87
      host: localhost
      port: 6379
      password:
      jedis:
        pool:
          max-active: 8
          max-wait: 1ms
          max-idle: 8
          min-idle: 0
      timeout: 10000ms

#mybatis 配置
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.attendance.model  # 注意：对应实体类的路径

#pagehelper分页插件
pagehelper:
  helperDialect: oracle
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#      defaultZone: http://10.32.250.85:8761/eureka/
    server:
      enable-self-preservation: false
      eviction-interval-timer-in-ms: 4000
    instance:
      #优先使用IP地址作为主机名的标识
      prefer-ip-address: true
      #续约任务调用时间间隔
      lease-renewal-interval-in-seconds: 5000
      #服务失效时间
      lease-expiration-duration-in-seconds: 5000

#-------------------------海康系统参数--------------------------------#
haikang:
  url: http://10.32.250.86:8080/person/getDoorEvents

#######################postgresql参数######################################
#本地测试
#postgreUrl: jdbc:postgresql://172.16.19.245:5432/cmsdb

#发布到88服务器
postgreUrl: jdbc:postgresql://10.32.194.3:5432/cmsdb
user: ivms8700_3rd
password: Abc12345+
driver: org.postgresql.Driver










