server:
  port: 8783
  tomcat:
    uri-encoding: UTF-8
  servlet:
    session:
      cookie:
        name: wechatsug

spring:
  application:
    name: wechatsug

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        enable_lazy_load_no_trans: true
    open-in-view: true
    database: oracle

  jackson:
    default-property-inclusion: non_null
  datasource:
    name: dataSource
    url: jdbc:oracle:thin:@10.32.250.83:1521:fyplatform
#    url: jdbc:oracle:thin:@10.71.177.199:1521:fyplatform
    username: fyplatform
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.OracleDriver
    filters: stat,wall,slf4j
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20


  #redis配置
  redis:
    database: 0
    host: 10.32.250.87
#    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: 1ms
        max-idle: 8
        min-idle: 0
    timeout: 10000ms

#mybatis 配置
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.wechatsug.model  # 注意：对应实体类的路径


pagehelper:
  helperDialect: oracle
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000
  instance:
    #优先使用IP地址作为主机名的标识
    prefer-ip-address: true
    #续约任务调用时间间隔
    lease-renewal-interval-in-seconds: 5000
    #服务失效时间
    lease-expiration-duration-in-seconds: 5000
